config/routes.rb
GameContestServer::Application.routes.draw do
  root 'users#index'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :referees
  resources :contests do
    resources :players, shallow: true
    resources :matches, shallow: true, only:[ :index, :show]
  end
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  

  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :referees
  has_many :players
  has_many :contests
  #attr_accessor :username, :password, :confirmation
  has_secure_password
  
  validates :username, presence: true
  validates_uniqueness_of :username
  validates_length_of :username, :maximum => 25
  
  validates :email, presence: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_user_logged_in, only:[:edit,:update,:index]
  before_action :ensure_correct_user, only:[:edit,:update]
  before_action :ensure_admin_user, only:[:destroy]
  before_action :ensure_not_logged_in, only: [:new, :create]
  
  respond_to :html, :json, :xml #lists all of the data types that you mkight expect to recieve
  
  def new #to get the login form
		@user = User.new
    respond_with(@user)
	end
  
  def create #to create the user and add to DB
		@user = User.new(permitted_params)
    if @user.save then
      flash[:success] = "Welcome"
      cookies.signed[:user_id] = @user.id
		end
    respond_with(@user)
  end
    
  def show
    @user = User.find(params[:id])
    respond_with(@user)
  end
    
  def index
    @users = User.all
    respond_with(@users)
  end
    
  def edit
  end
    
  def update
    @user = User.find(params[:id])
      if @user.update(permitted_params) then
        flash[:success] = "Successfully made updates to #{@username}"
      end
      respond_with(@user)
  end
    
  def destroy
    @user = User.find(params[:id])
    if @user.admin
      redirect_to root_path
    end
    @user.destroy
    flash[:success] = "Successfully deleted user"      
    #redirect_to users_path
    respond_with(@user)
  end  
  
  def ensure_user_logged_in
    redirect_to login_path unless logged_in?
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    redirect_to root_path, flash: { :danger => "You are logged in and cannot perform that action!" } unless current_user?(@user)
  end
    
  def ensure_admin_user
    redirect_to root_path, flash: { :danger => "You are logged in and cannot perform that action!" } unless current_user.admin?
  end
    
  def ensure_not_logged_in
    redirect_to root_path, flash: { :danger => "You are logged in and cannot perform that action!" } unless !logged_in?
  end  
    
  private 
    def permitted_params
      params.require(:user).permit(:username, :password, :password_confirmation, :email)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<li> 
  <%= link_to user.username, user_path(user) %>
  <% if current_user %>
    <% if(current_user.admin) %>
      <% if !user.admin %>
      |
      <%= link_to 'delete', user_path(user), method: :delete, data: {confirm: 'Do you really want to delete user: #{user.username}?' } %> 
      <% end %>
    <% end %>
  <% end %>
</li>

app/views/users/_user_form.html.erb
  <% if @user.errors.any? %>
  <div class='alert alert-danger' >
  <p> There are <%= @user.errors.count %> errors </p>
  </div>
    <ul>
        <% @user.errors.full_messages.each do |message|%>
          <li><%=message%></li>
        <% end %>
    </ul>
  <% end %>
    
  <div class='form-group'>
  <%= f.label :username, 'Username:' %>	
  <%= f.text_field :username, class: 'form-control' %>
  </div>

  <div class='form-group'>
  <%= f.label :password, 'Password:' %>	
  <%= f.text_field :password, type:"password", class: 'form-control'%>
  </div>
    
  <div class='form-group'>
  <%= f.label :password_confirmation, 'Confirmation:' %>	
  <%= f.text_field :password_confirmation, type:"password", class: 'form-control'%>
  </div>
    
  <div class='form-group'>
  <%= f.label :email, "Email:" %>
  <%= f.text_field :email, class: 'form-control' %>
  </div>

app/views/users/_user_players.html.erb
<li><%= link_to player.name, player_path(player) %> |
     <%= link_to "edit", edit_player_path(player) %>
      <% if current_user?(player.user) %>
       | <%# link_to "delete", player_path(player), method: :delete, data: { confirm: "Are you sure you want to delete #{player.name}?" } %><% end %></li>

app/views/users/_user_referees_html.erb
<li><%= link_to referee.name, referee_path(referee) %> |
     <%= link_to "edit", edit_referee_path(referee) %>
      <% if logged_in? %>
       | <%# link_to "delete", referee_path(referee), method: :delete, data: { confirm: "Are you sure you want to delete #{referee.name}?" } %><% end %></li>

app/views/users/edit.html.erb
<h1> Edit Account Info</h1>
<%= form_for @user do |form| %>
<%= render 'user_form', f: form %>
<%= form.submit 'Update account' %>
<% end %>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<H1>List of users</H1>
<% if flash[:success] %>
  <div class='alert alert-success' >
    <p>You have successfully delete a user</p>
  </div>
<% end %>
<h3><%= @users.length%> users</h3>
<ul>
  <%= render @users %>
</ul>

app/views/users/new.html.erb
<h1>Sign up!</h1>
<%= form_for @user do |form| %>
<%= render 'user_form', f: form %>
<%= f.submit 'Create new account' %>
<% end %>

app/views/users/show.html.erb
<H1>User info</H1>
<% if flash[:success] %>
  <div class='alert alert-success' >
    <p>Welcome</p>
  </div>
<% end %>
<p>Name: <%= @user.username %> | <%= link_to "edit", edit_user_path(@user) %></p>

<ul>
  <li>Email: <%= @user.email %></li>
  <li>Chat Url: <%= @user.chat_url %></li>
</ul>

<% if  @user.contest_creator? %>
<h2>Referees</h2>
<h4><%= @user.referees.length%> referees</h4>
<ul>
  <% @user.referees.each do |list| %>
  <li> <%=  link_to list.name, referee_path(list) %>
    |
  <%= link_to 'delete', referee_path(list), method: :delete, data: {confirm: 'Do you really want to delete this referee?' } %> </li><% end %>
<%# render "users/_user_referees.html.erb", collection: @user.referees, as: :referee%>
</ul>
<p><%= link_to "New Referee", new_referee_path %></p>
<% end %>

<h2>Players</h2>
<h4><%=@user.players.length%> players</h4>
<ul>
  <% @user.players.each do |list| %>
  <li> <%= link_to list.name, player_path(list) %>
    |
  <%= link_to 'delete', player_path(list), method: :delete, data: {confirm: 'Do you really want to delete this player?' } %> </li><% end %>
<%# render "users/_user_players.html.erb", collection: @user.players, as: :player%>
</ul>